---
language: go

go:
  - "1.10"

go_import_path: github.com/FidelityInternational/possum

before_install:
  - go get github.com/pierrre/gotestcover
  - go get golang.org/x/tools/cover

script:
  - gotestcover -coverprofile=coverage.txt -race -covermode=atomic -v $(go list ./... | grep -v '/vendor/')

after_success:
  - bash <(curl -s https://codecov.io/bash)
