---
language: go

go:
  - 1.13.x

go_import_path: github.com/FidelityInternational/possum

before_install:
  - go get github.com/pierrre/gotestcover
  - go get golang.org/x/tools/cover

script:
  - go test -mod=vendor -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
