---
language: go

go:
  - "1.11"

go_import_path: github.com/FidelityInternational/possum

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
